// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AlertSettings = { desktop_enabled: boolean, min_profit_per_ton: number, min_cr_per_hour: bigint, max_distance_ly: number, cooldown_minutes: number, webhook_url: string | null, };
