// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DataSourceSettings = { eddn_relay_url: string, journal_dir: string | null, inara_api_key: string | null, spansh_galaxy_downloaded: boolean, database_url: string | null, };
