// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Diagnostics = { db_dialect: string, db_bytes: bigint, snapshot_count: bigint, oldest_snapshot: string | null, newest_snapshot: string | null, eddn_connected: boolean, eddn_msgs_per_sec: number, eddn_last_msg_at: string | null, journal_status: string, };
