// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FirehoseTick = { at: string, system: string, station: string, commodities_updated: number, };
