// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RouteLeg = { from_system: string, from_station: string, to_system: string, to_station: string, commodity: string, buy_price: number, sell_price: number, profit_per_ton: number, supply: number, demand: number, jumps: number, distance_ly: number, recorded_at: string, };
