// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShipSpec = { ship_type: string, cargo_capacity: number, jump_range_ly: number, pad_size_max: string, };
