// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpanshPhase } from "./SpanshPhase";

export type SpanshProgress = { phase: SpanshPhase, bytes_done: bigint, bytes_total: bigint | null, systems_imported: bigint, message: string | null, };
