// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserState = { current_system: string | null, current_station: string | null, ship_type: string | null, cargo_capacity: number | null, jump_range_ly: number | null, credits: bigint | null, pad_size_max: string | null, updated_at: string, };
